# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1eab70170c75dcbe94f0be500ffc703d"
name = "dev-checkout-201"
handle = "dev-checkout-201"
application_url = "https://uniform-ati-hello-kilometers.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-editions-checkout-201.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products,write_publications"

[auth]
redirect_urls = [
  "https://uniform-ati-hello-kilometers.trycloudflare.com/auth/callback",
  "https://uniform-ati-hello-kilometers.trycloudflare.com/auth/shopify/callback",
  "https://uniform-ati-hello-kilometers.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
